### ISSUE TITLE
ValueError: Keys cannot be empty

### ISSUE THREAD

**Issue by xiangwf** [py2neo-org/py2neo#758]
when I use the code **list(matcher.match("Node", id="0"))** and **print(graph.run("match (n) where id(n)=1 return n").data())** the same error always happended.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiang/.conda/envs/py2neoV4/lib/python3.7/site-packages/py2neo/data.py", line 771, in __repr__
    return Walkable.__repr__(self)
  File "/home/xiang/.conda/envs/py2neoV4/lib/python3.7/site-packages/py2neo/data.py", line 673, in __repr__
    return xstr(cypher_repr(self))
  File "/home/xiang/.conda/envs/py2neoV4/lib/python3.7/site-packages/py2neo/cypher/__init__.py", line 71, in cypher_repr
    return encoder.encode_value(value)
  File "/home/xiang/.conda/envs/py2neoV4/lib/python3.7/site-packages/py2neo/cypher/encoding.py", line 178, in encode_value
    return self.encode_node(value)
  File "/home/xiang/.conda/envs/py2neoV4/lib/python3.7/site-packages/py2neo/cypher/encoding.py", line 233, in encode_node
    return self._encode_node(node, self.node_template)
  File "/home/xiang/.conda/envs/py2neoV4/lib/python3.7/site-packages/py2neo/cypher/encoding.py", line 272, in _encode_node
    ).strip() + u")"
  File "/home/xiang/.conda/envs/py2neoV4/lib/python3.7/site-packages/py2neo/cypher/encoding.py", line 62, in __repr__
    return "".join(":%s" % self.__encoder.encode_key(e) for e in sorted(self))
  File "/home/xiang/.conda/envs/py2neoV4/lib/python3.7/site-packages/py2neo/cypher/encoding.py", line 62, in <genexpr>
    return "".join(":%s" % self.__encoder.encode_key(e) for e in sorted(self))
  File "/home/xiang/.conda/envs/py2neoV4/lib/python3.7/site-packages/py2neo/cypher/encoding.py", line 158, in encode_key
    raise ValueError("Keys cannot be empty")
**ValueError: Keys cannot be empty**
**environement: Python 3.7.3, py2neo 4.3.0**
can you help me soon?

**Comment by technige** [comment]
The match method accepts a label name (which I assume `"Node"` here is not) and a property key-value pair. To match by internal ID, use the special property value `__id__` and pass the ID value as an integer (not a string).
