### ISSUE TITLE
ConstraintValidationFailed not found in py2neo.cypher.error.schema

### ISSUE THREAD

**Issue by gracefullife** [py2neo-org/py2neo#764]
I think ConstraintVerificationFailure is correct.
https://github.com/technige/py2neo/blob/1d43dda431e94991e38a962d5b592e35ff298a4d/py2neo/database.py#L719
https://py2neo.org/2.0/cypher.html#py2neo.cypher.error.schema.ConstraintVerificationFailure

error is below
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mongo_connector/oplog_manager.py", line 668, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python3.7/site-packages/mongo_connector/oplog_manager.py", line 651, in upsert_all
    dm.bulk_upsert(docs_to_dump(from_coll), mapped_ns, long_ts)
  File "/usr/local/lib/python3.7/site-packages/mongo_connector/util.py", line 44, in wrapped
    raise new_type(str(exc_value)).with_traceback(exc_tb)
  File "/usr/local/lib/python3.7/site-packages/mongo_connector/util.py", line 33, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mongo_connector/doc_managers/neo4j_doc_manager.py", line 89, in bulk_upsert
    tx.commit()
  File "/usr/local/lib/python3.7/site-packages/py2neo/cypher/core.py", line 333, in commit
    return self.post(self.__commit or self.__begin_commit)
  File "/usr/local/lib/python3.7/site-packages/py2neo/cypher/core.py", line 288, in post
    raise self.error_class.hydrate(error)
  File "/usr/local/lib/python3.7/site-packages/py2neo/cypher/error/core.py", line 54, in hydrate
    error_cls = getattr(error_module, title)
mongo_connector.doc_managers.error_handler.Neo4jOperationFailed: module 'py2neo.cypher.error.schema' has no attribute 'ConstraintValidationFailed'
```

**Comment by technige** [comment]
This issue has no code to recreate, and seems to come from a third party library. Therefore, closing.
