### ISSUE TITLE
OGM - Logging Error when one of the properties is a datetime object

### ISSUE THREAD

**Issue by cholmes90s** [py2neo-org/py2neo#813]
Hi,

When one of the node properties inserted to the database is a python datetime object the following logging error is printed. Everything else works fine , the node appears on the database but when lots of nodes are inserted with datetime object properties, it spams the stdout.

`--- Logging error ---

Traceback (most recent call last):

  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)

  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)

  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 664, in format
    record.message = record.getMessage()

  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\connect\packstream.py", line 57, in __repr__
    return "Structure[#%02X](%s)" % (self.tag, ", ".join(map(repr, self.fields)))

TypeError: %X format: an integer is required, not bytes

Call stack:

  File "C:\Users\user\Documents\programming\Demo\Demo.py", line 21, in <module>
    graph_connection.push(Ford)

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\database.py", line 569, in push
    tx.push(subgraph)

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\database.py", line 1107, in push
    return push(self)

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\ogm.py", line 466, in __db_push__
    tx.merge(node)

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\database.py", line 1067, in merge
    merge(self, primary_label, primary_key)

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\data.py", line 623, in __db_merge__
    merge_subgraph(tx, self, primary_label, primary_key)

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\internal\operations.py", line 166, in merge_subgraph
    identities = list(_merge_nodes(tx, pl, pk, labels,

  File C:\Users\user\Documents\programming\Demo\lib\site-packages\py2neo\internal\operations.py", line 105, in _merge_nodes
    for record in tx.run(cypher, x=data):

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\database.py", line 923, in run
    result = self._connector.run_in_tx(self._transaction, cypher, parameters, hydrant)

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\connect\__init__.py", line 721, in run_in_tx
    result = cx.run_in_tx(tx, cypher, parameters)

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\connect\bolt.py", line 234, in run_in_tx
    return self._run(tx.graph_name, cypher, parameters or {})

  File "C:\Users\user\Documents\programming\Demo\venv\lib\site-packages\py2neo\connect\bolt.py", line 455, in _run
    log.debug("[#%04X] C: RUN %r %r %r", self.local_port, cypher, parameters, extra or {})

Unable to print the message and arguments - possible formatting error.

Use the traceback above to help find the error.`

**Comment by technige** [comment]
Closing, as this code no longer exists.
