### ISSUE TITLE
IndexError: index out of range on 2021.2.0

### ISSUE THREAD

**Issue by p1nox** [py2neo-org/py2neo#920]
Py2neo version: 2021.2.0

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/deployment/elementus-neo4j/tools/cli/risk_scores.py", line 104, in <module>
    main(**kwargs)
  File "/home/ubuntu/deployment/elementus-neo4j/tools/cli/risk_scores.py", line 86, in main
    return risk_scoring_job(config_db, btc_neo4j_serv, eth_neo4j_serv)
  File "/home/ubuntu/deployment/elementus-neo4j/tools/cli/risk_scores.py", line 57, in risk_scoring_job
    eth_risk_scoring_neo4j.run()
  File "/home/ubuntu/deployment/elementus-neo4j/tools/core/models/eth_risk_scoring_neo4j.py", line 38, in run
    self.run_by_category(category, source_node)
  File "/home/ubuntu/deployment/elementus-neo4j/tools/core/models/eth_risk_scoring_neo4j.py", line 67, in run_by_category
    return self.service.run(q)
  File "/home/ubuntu/deployment/elementus-neo4j/tools/core/connections/neo4j_service.py", line 25, in run
    return self.db.run(query)
  File "/home/ubuntu/deployment/elementus-neo4j/venv/lib/python3.7/site-packages/py2neo/database.py", line 405, in run
    return self.auto().run(cypher, parameters, **kwparameters)
  File "/home/ubuntu/deployment/elementus-neo4j/venv/lib/python3.7/site-packages/py2neo/database.py", line 992, in run
    self._connector.pull(result, -1)
  File "/home/ubuntu/deployment/elementus-neo4j/venv/lib/python3.7/site-packages/py2neo/client/__init__.py", line 1434, in pull
    cx.pull(result, n=n)
  File "/home/ubuntu/deployment/elementus-neo4j/venv/lib/python3.7/site-packages/py2neo/client/bolt.py", line 971, in pull
    self._sync(response)
  File "/home/ubuntu/deployment/elementus-neo4j/venv/lib/python3.7/site-packages/py2neo/client/bolt.py", line 775, in _sync
    self._wait(response)
  File "/home/ubuntu/deployment/elementus-neo4j/venv/lib/python3.7/site-packages/py2neo/client/bolt.py", line 770, in _wait
    self._fetch()
  File "/home/ubuntu/deployment/elementus-neo4j/venv/lib/python3.7/site-packages/py2neo/client/bolt.py", line 745, in _fetch
    tag, fields = self.read_message()
  File "/home/ubuntu/deployment/elementus-neo4j/venv/lib/python3.7/site-packages/py2neo/client/bolt.py", line 672, in read_message
    tag, fields = self._reader.read_message()
  File "/home/ubuntu/deployment/elementus-neo4j/venv/lib/python3.7/site-packages/py2neo/client/bolt.py", line 165, in read_message
    _, n = divmod(message[0], 0x10)
IndexError: index out of range
```

**Comment by littlemilkwu** [comment]
py2neo version : 2021.1.5
neo4j Graph DBMS : 4.3.2

I get the same error too !
I am importing some large csv file into neo4j, 1.2 million row of data and the csv file is 24 MB.
this cypher run OK on neo4j browser
but on the py2neo, it will crash.

cypher : 
`uu_data = graph.run("""
    CALL apoc.periodic.iterate(
    "
        CALL apoc.load.csv(
            'WUU/WUU_edgelist_20year.csv', {header: true}
        )
        YIELD map AS LINE RETURN LINE
    ",
    "
        MERGE (s:User {uid: LINE['n1']})
        MERGE (t:User {uid: LINE['n2']})
        MERGE (s)-[:WidthRelation {weight: toInteger(LINE['weight'])}]-(t)
    ", {batchSize: 10000, iterateList: true}
)
""")`

error : 
`IndexError: index out of range
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-a54ac50424b1> in <module>
      1 # import csv
      2 print("20 year")
----> 3 uu_data = graph.run("""
      4     CALL apoc.periodic.iterate(
      5     "

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/database.py in run(self, cypher, parameters, **kwparameters)
    403         :return:
    404         """
--> 405         return self.auto().run(cypher, parameters, **kwparameters)
    406 
    407     def evaluate(self, cypher, parameters=None, **kwparameters):

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/database.py in run(self, cypher, parameters, **kwparameters)
    976                 result = self._connector.run(self.ref, cypher, parameters)
    977             else:
--> 978                 result = self._connector.auto_run(cypher, parameters,
    979                                                   graph_name=self.graph.name,
    980                                                   readonly=self.readonly)

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/__init__.py in auto_run(self, cypher, parameters, pull, graph_name, readonly)
   1341             if pull != 0:
   1342                 try:
-> 1343                     cx.pull(result, n=pull)
   1344                 except TypeError:
   1345                     # If the RUN fails, so will the PULL, due to

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in pull(self, result, n, capacity)
    941         result.append(response, final=(n == -1))
    942         try:
--> 943             self._sync(response)
    944         except BrokenWireError as error:
    945             result.transaction.mark_broken()

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in _sync(self, *responses)
    745         self.send()
    746         for response in responses:
--> 747             self._wait(response)
    748 
    749     def _audit(self, task):

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in _wait(self, response)
    740         """
    741         while not response.full() and not response.done():
--> 742             self._fetch()
    743 
    744     def _sync(self, *responses):

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in _fetch(self)
    715         failed state into an exception.
    716         """
--> 717         tag, fields = self.read_message()
    718         if tag == 0x70:
    719             self._responses.popleft().set_success(**fields[0])

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in read_message(self)
    642 
    643     def read_message(self):
--> 644         tag, fields = self._reader.read_message()
    645         if tag == 0x71:
    646             # If a RECORD is received, check for more records

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in read_message(self)
     94                 chunks.append(self.wire.read(size))
     95         message = b"".join(chunks)
---> 96         _, n = divmod(message[0], 0x10)
     97         try:
     98             unpacker = UnpackStream(message, offset=2)

IndexError: index out of range`

**Comment by littlemilkwu** [comment]
I try to downgrade py2neo to 2020.0.0 version,
neo4j DBMS version still 4.3.2

still have this problem ( but error is different )
![image](https://user-images.githubusercontent.com/44579618/132096736-058f95dc-71ea-4fff-b4cb-730c29c46233.png)

```
IndexError: index out of range
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-a54ac50424b1> in <module>
      1 # import csv
      2 print("20 year")
----> 3 uu_data = graph.run("""
      4     CALL apoc.periodic.iterate(
      5     "

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/database.py in run(self, cypher, parameters, **kwparameters)

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/database.py in run(self, cypher, parameters, **kwparameters)

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/__init__.py in auto_run(self, cypher, parameters, pull, graph_name, readonly)

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in pull(self, result, n, capacity)

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in _sync(self, *responses)
    745         except IndexError:
    746             return None
--> 747 
    748     def peek_records(self, n):
    749         return islice(self._records, 0, n)

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in _wait(self, response)
    740         return bool(self._records)
    741 
--> 742     def take_record(self):
    743         try:
    744             return self._records.popleft()

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in _fetch(self)
    715     #   3 = ignored
    716 
--> 717     def __init__(self, capacity=-1, vital=False):
    718         super(BoltResponse, self).__init__()
    719         self.capacity = capacity

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in read_message(self)
    642 class BoltResult(ItemizedTask, Result):
    643     """ The result of a query carried out over a Bolt connection.
--> 644 
    645     Implementation-wise, this form of query is comprised of a number of
    646     individual message exchanges. Each of these exchanges may succeed

~/opt/anaconda3/lib/python3.8/site-packages/py2neo/client/bolt.py in read_message(self)
     94         return PackStreamHydrant(graph)
     95 
---> 96     @classmethod
     97     def protocol_catalogue(cls):
     98         return [bolt.protocol_version for bolt in Bolt._walk_subclasses()]

IndexError: index out of range
```
