### ISSUE TITLE
IndexError: index out of range (works fine in Neo4j)

### ISSUE THREAD

**Issue by TbsHbnthl** [py2neo-org/py2neo#922]
I'm running the following line in python with py2neo:

`q_path = graph.run(f"MATCH (n1)-[]-(p1:Patient)-[]-(p2:General_Study)-[]-(n2) RETURN p1.nodeUID as pathNode1, p2.nodeUID as pathNode2, n1 as NeighbourOfp1, n2 as NeighbourOfp2, gds.alpha.linkprediction.commonNeighbors(p1,n1) as scoren1, gds.alpha.linkprediction.commonNeighbors(p2,n2) as scoren2 ORDER BY p1.nodeUID, p2.nodeUID, scoren1 DESC, scoren2 DESC LIMIT 1").data()`

In the browser interface this query works just fine. In py2neo I get the following error:

Traceback (most recent call last):
  File "/Users/.../test4.py", line 178, in <module>
    create_sents()
  File "/Users/.../test4.py", line 65, in create_sents
    q_path = graph.run(f"MATCH (n1)-[]-(p1:Patient)-[]-(p2:General_Study)-[]-(n2) RETURN p1.nodeUID as pathNode1, p2.nodeUID as pathNode2, n1 as NeighbourOfp1, n2 as NeighbourOfp2, gds.alpha.linkprediction.commonNeighbors(p1,n1) as scoren1, gds.alpha.linkprediction.commonNeighbors(p2,n2) as scoren2 ORDER BY p1.nodeUID, p2.nodeUID, scoren1 DESC, scoren2 DESC LIMIT 1").data()
  File "/usr/local/lib/python3.8/site-packages/py2neo/database.py", line 405, in run
    return self.auto().run(cypher, parameters, **kwparameters)
  File "/usr/local/lib/python3.8/site-packages/py2neo/database.py", line 978, in run
    result = self._connector.auto_run(cypher, parameters,
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/__init__.py", line 1343, in auto_run
    cx.pull(result, n=pull)
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 943, in pull
    self._sync(response)
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 747, in _sync
    self._wait(response)
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 742, in _wait
    self._fetch()
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 717, in _fetch
    tag, fields = self.read_message()
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 644, in read_message
    tag, fields = self._reader.read_message()
  File "/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 96, in read_message
    _, n = divmod(message[0], 0x10)
IndexError: index out of range

I don't get it. Can anyone tell me why it works in the browser interface but not via py2neo?

**Comment by deftbox-meet** [comment]
@TbsHbnthl  Any solutions you have found ?

**Comment by TbsHbnthl** [comment]
Not really. But a workaround: I query the graph in the neo4j interface and export the result as a CSV file. This can then be read by my program.

**Comment by littlemilkwu** [comment]
I just switch to use neo4j official python driver.

**Comment by motey** [comment]
dup of #918
