### ISSUE TITLE
RuntimeError: Can't begin a new transaction

### ISSUE THREAD

**Issue by wbcai-wmh** [py2neo-org/py2neo#956]
Traceback (most recent call last):
  File "/Users/KGQA_Version.Amme/QASystemOnMedicalKG-AmmeRevision/build_medicalgraph.py", line 346, in <module>
    handler.create_graphnodes();
  File "/Users/KGQA_Version.Amme/QASystemOnMedicalKG-AmmeRevision/build_medicalgraph.py", line 250, in create_graphnodes
    self.create_diseases_nodes(disease_infos)
  File "/Users/KGQA_Version.Amme/QASystemOnMedicalKG-AmmeRevision/build_medicalgraph.py", line 237, in create_diseases_nodes
    self.g.create(node)
  File "/Users/anaconda3/envs/torch107/lib/python3.7/site-packages/py2neo/database.py", line 362, in create
    with self.begin() as tx:
  File "/Users/anaconda3/envs/torch107/lib/python3.7/site-packages/py2neo/database.py", line 353, in begin
    return Transaction(self, autocommit)
  File "/Users/anaconda3/envs/torch107/lib/python3.7/site-packages/py2neo/database.py", line 781, in __init__
    self.transaction = self.connector.begin()
  File "/Users/anaconda3/envs/torch107/lib/python3.7/site-packages/py2neo/internal/connectors.py", line 398, in begin
    raise RuntimeError("Can't begin a new transaction")
RuntimeError: Can't begin a new transaction

Process finished with exit code 1

how can I solve it ? thank you!

**Comment by GdxiASD** [comment]
I have the same problem, have you make it ?

**Comment by wbcai-wmh** [comment]
已收到您的邮件:-）
